#!/usr/bin/env python3
"""Validate independent two-person review packets and report paper readiness.

The committed packets intentionally start as ``pending``.  This checker makes
the work assignable before measurement without pretending that an AI or one
maintainer constitutes two independent reviewers.  Static validation exits 0
for complete, well-formed pending packets; readiness modes exit 2 until the
required human sign-offs are present.  Post-measurement approvals additionally
bind the canonical final-evidence root generated by the verification profile.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_MANIFEST = ROOT / "docs" / "reviews" / "paper" / "manifest.yaml"
SCHEMA_PATH = ROOT / "docs" / "reviews" / "paper-review-v2.schema.json"
REVIEW_ID_RE = re.compile(r"^[a-z0-9][a-z0-9._-]{2,127}$")
PACKET_KEYS = {
    "schema_version",
    "review_id",
    "status",
    "title",
    "review_phase",
    "final_evidence_root_sha256",
    "source_revision_policy",
    "scope",
    "threat_model",
    "secret_origin",
    "observed_dependency",
    "declassification_predicate",
    "public_transcript",
    "security_argument",
    "known_limitations",
    "evidence",
    "expected_evidence",
    "reviewers",
    "expiry_conditions",
}
FINAL_STATUSES = {"reviewed", "disputed", "expired"}
REVISION_RE = re.compile(r"^[0-9a-f]{40}$")
SHA256_RE = re.compile(r"^[0-9a-f]{64}$")


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def _load_yaml(path: Path) -> dict[str, Any]:
    raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise ValueError(f"{path}: root must be a mapping")
    return raw


def _repo_path(root: Path, value: Any, label: str) -> Path:
    if not isinstance(value, str) or not value:
        raise ValueError(f"{label} must be a non-empty repository-relative path")
    raw = Path(value)
    if raw.is_absolute() or ".." in raw.parts:
        raise ValueError(f"{label} escapes repository: {value!r}")
    resolved_root = root.resolve()
    candidate = resolved_root / raw
    if candidate.is_symlink() or any(
        parent.is_symlink()
        for parent in candidate.parents
        if parent != resolved_root and parent.is_relative_to(resolved_root)
    ):
        raise ValueError(f"{label} contains a symlink: {value!r}")
    resolved = candidate.resolve()
    if not resolved.is_relative_to(resolved_root):
        raise ValueError(f"{label} escapes repository: {value!r}")
    return resolved


def _git(root: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", *args],
        cwd=root,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=True,
        timeout=30,
    )
    return result.stdout.strip()


def _string_list(value: Any, label: str, *, allow_empty: bool = False) -> list[str]:
    if not isinstance(value, list) or (not allow_empty and not value):
        raise ValueError(
            f"{label} must be a {'possibly empty ' if allow_empty else 'non-empty '}list"
        )
    if any(not isinstance(item, str) or not item.strip() for item in value):
        raise ValueError(f"{label} must contain non-empty strings")
    return value


def evidence_manifest_sha256(packet: dict[str, Any], *, root: Path) -> str:
    """Bind the complete review policy plus the bytes of every evidence file.

    ``status`` and ``reviewers`` are excluded to avoid a self-referential
    signature: reviewers calculate this digest over the pending contract, then
    their unanimous decisions move the packet to ``reviewed``.  Every claim,
    scope, limitation, expiry condition, and expected-evidence requirement is
    included, so none can change after approval without invalidating it.
    """

    entries: list[dict[str, str]] = []
    for value in _string_list(packet.get("evidence"), "evidence", allow_empty=True):
        path = _repo_path(root, value, "evidence")
        if not path.is_file() or path.is_symlink():
            raise ValueError(f"evidence must be a regular file: {value}")
        entries.append(
            {
                "path": value,
                "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
            }
        )
    contract = {key: packet.get(key) for key in sorted(PACKET_KEYS - {"status", "reviewers"})}
    canonical = json.dumps(
        {"review_contract": contract, "evidence_files": entries},
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    return hashlib.sha256(canonical).hexdigest()


def validate_packet(
    packet: dict[str, Any],
    *,
    root: Path,
    path: Path,
    minimum_reviewers: int,
    required_before_measurement: bool,
) -> list[str]:
    errors: list[str] = []
    label = path.relative_to(root) if path.is_relative_to(root) else path
    unknown = sorted(set(packet) - PACKET_KEYS)
    missing = sorted(PACKET_KEYS - set(packet))
    if unknown:
        errors.append(f"{label}: unknown keys {unknown}")
    if missing:
        errors.append(f"{label}: missing keys {missing}")
        return errors
    if packet["schema_version"] != "2.0":
        errors.append(f"{label}: schema_version must be '2.0'")
    review_id = packet["review_id"]
    if not isinstance(review_id, str) or not REVIEW_ID_RE.fullmatch(review_id):
        errors.append(f"{label}: invalid review_id={review_id!r}")
    status = packet["status"]
    if status not in {"pending", "reviewed", "disputed", "expired"}:
        errors.append(f"{label}: invalid status={status!r}")
    phase = packet["review_phase"]
    if phase not in {"pre-measurement", "post-measurement"}:
        errors.append(f"{label}: invalid review_phase={phase!r}")
    if required_before_measurement and phase != "pre-measurement":
        errors.append(f"{label}: pre-measurement-required packet has phase={phase!r}")
    if not required_before_measurement and phase != "post-measurement":
        errors.append(f"{label}: post-measurement packet has phase={phase!r}")
    final_evidence_root = packet["final_evidence_root_sha256"]
    if phase == "pre-measurement":
        if final_evidence_root is not None:
            errors.append(f"{label}: pre-measurement packet cannot bind final evidence")
    elif final_evidence_root is not None and (
        not isinstance(final_evidence_root, str) or not SHA256_RE.fullmatch(final_evidence_root)
    ):
        errors.append(f"{label}: final_evidence_root_sha256 must be null or lowercase SHA-256")
    if (
        phase == "post-measurement"
        and status in {"reviewed", "disputed"}
        and (
            not isinstance(final_evidence_root, str) or not SHA256_RE.fullmatch(final_evidence_root)
        )
    ):
        errors.append(f"{label}: completed post-measurement review must bind final evidence")
    if packet["source_revision_policy"] != "exact-clean-git-head-at-review":
        errors.append(f"{label}: source_revision_policy drift")

    scopes = packet["scope"]
    if not isinstance(scopes, list) or not scopes:
        errors.append(f"{label}: scope must be a non-empty list")
    else:
        seen_scope: set[tuple[str, str, str]] = set()
        for index, scope in enumerate(scopes):
            if not isinstance(scope, dict) or set(scope) != {"target", "harness", "build_scope"}:
                errors.append(f"{label}: scope[{index}] must contain target/harness/build_scope")
                continue
            values = (scope["target"], scope["harness"], scope["build_scope"])
            if any(not isinstance(value, str) or not value.strip() for value in values):
                errors.append(f"{label}: scope[{index}] values must be non-empty strings")
            elif values in seen_scope:
                errors.append(f"{label}: duplicate scope {values}")
            seen_scope.add(values)

    for field in (
        "title",
        "threat_model",
        "secret_origin",
        "observed_dependency",
        "declassification_predicate",
        "public_transcript",
        "security_argument",
    ):
        value = packet[field]
        if not isinstance(value, str) or not value.strip():
            errors.append(f"{label}: {field} must be a non-empty string")
    for field in ("known_limitations", "expiry_conditions"):
        try:
            _string_list(packet[field], f"{label}: {field}")
        except ValueError as exc:
            errors.append(str(exc))
    for field in ("evidence", "expected_evidence"):
        try:
            string_values = _string_list(packet[field], f"{label}: {field}", allow_empty=True)
        except ValueError as exc:
            errors.append(str(exc))
            string_values = []
        if field == "evidence":
            for value in string_values:
                try:
                    evidence_path = _repo_path(root, value, f"{label}: evidence")
                except ValueError as exc:
                    errors.append(str(exc))
                    continue
                if not evidence_path.exists():
                    errors.append(f"{label}: evidence path missing: {value}")
    try:
        evidence_digest = evidence_manifest_sha256(packet, root=root)
    except (OSError, ValueError) as exc:
        errors.append(f"{label}: cannot hash evidence manifest: {exc}")
        evidence_digest = ""

    reviewers = packet["reviewers"]
    if not isinstance(reviewers, list):
        errors.append(f"{label}: reviewers must be a list")
        reviewers = []
    reviewer_ids: set[str] = set()
    decisions: list[str] = []
    for index, reviewer in enumerate(reviewers):
        if not isinstance(reviewer, dict):
            errors.append(f"{label}: reviewers[{index}] must be a mapping")
            continue
        expected = {
            "id",
            "human_reviewer",
            "affiliation_or_role",
            "independent_from_artifact_author",
            "decision",
            "reviewed_at",
            "reviewed_commit",
            "evidence_manifest_sha256",
            "notes",
        }
        if set(reviewer) != expected:
            errors.append(f"{label}: reviewers[{index}] fields must be {sorted(expected)}")
            continue
        reviewer_id = reviewer["id"]
        if not isinstance(reviewer_id, str) or not REVIEW_ID_RE.fullmatch(reviewer_id):
            errors.append(f"{label}: reviewers[{index}] has invalid id")
        elif reviewer_id in reviewer_ids:
            errors.append(f"{label}: duplicate reviewer id {reviewer_id!r}")
        reviewer_ids.add(str(reviewer_id))
        if reviewer["human_reviewer"] is not True:
            errors.append(f"{label}: reviewer {reviewer_id!r} is not declared human")
        if (
            not isinstance(reviewer["affiliation_or_role"], str)
            or not reviewer["affiliation_or_role"].strip()
        ):
            errors.append(f"{label}: reviewer {reviewer_id!r} requires affiliation_or_role")
        if reviewer["independent_from_artifact_author"] is not True:
            errors.append(f"{label}: reviewer {reviewer_id!r} is not independent")
        decision = reviewer["decision"]
        if decision not in {"approve", "reject", "abstain"}:
            errors.append(f"{label}: reviewer {reviewer_id!r} has invalid decision")
        decisions.append(str(decision))
        reviewed_at = reviewer["reviewed_at"]
        if not isinstance(reviewed_at, str) or not reviewed_at.strip():
            errors.append(f"{label}: reviewer {reviewer_id!r} requires reviewed_at")
        else:
            try:
                parsed_reviewed_at = datetime.fromisoformat(reviewed_at.replace("Z", "+00:00"))
            except ValueError:
                errors.append(f"{label}: reviewer {reviewer_id!r} reviewed_at is not ISO-8601")
            else:
                if parsed_reviewed_at.tzinfo is None:
                    errors.append(
                        f"{label}: reviewer {reviewer_id!r} reviewed_at requires a timezone"
                    )
        reviewed_commit = reviewer["reviewed_commit"]
        if not isinstance(reviewed_commit, str) or not REVISION_RE.fullmatch(reviewed_commit):
            errors.append(f"{label}: reviewer {reviewer_id!r} reviewed_commit is malformed")
        recorded_evidence_digest = reviewer["evidence_manifest_sha256"]
        if (
            not isinstance(recorded_evidence_digest, str)
            or not SHA256_RE.fullmatch(recorded_evidence_digest)
            or recorded_evidence_digest != evidence_digest
        ):
            errors.append(f"{label}: reviewer {reviewer_id!r} evidence manifest hash mismatch")
        if not isinstance(reviewer["notes"], str) or not reviewer["notes"].strip():
            errors.append(f"{label}: reviewer {reviewer_id!r} requires notes")

    if status == "reviewed":
        if len(reviewers) < minimum_reviewers:
            errors.append(
                f"{label}: reviewed requires at least {minimum_reviewers} independent reviewers"
            )
        if any(decision != "approve" for decision in decisions):
            errors.append(f"{label}: reviewed requires unanimous approve decisions")
    elif status == "disputed":
        if len(reviewers) < minimum_reviewers or "reject" not in decisions:
            errors.append(f"{label}: disputed requires quorum and at least one reject")
    elif status == "pending" and reviewers:
        errors.append(f"{label}: partial sign-offs must remain external until quorum is complete")
    return errors


def evaluate_manifest(
    manifest_path: Path = DEFAULT_MANIFEST,
    *,
    root: Path = ROOT,
) -> tuple[dict[str, Any], list[str]]:
    errors: list[str] = []
    try:
        schema = json.loads((root / SCHEMA_PATH.relative_to(ROOT)).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return {}, [f"review schema unreadable: {exc}"]
    if set(schema.get("required", [])) != PACKET_KEYS:
        errors.append("paper review JSON schema required fields drift from checker")
    if set(schema.get("properties", {})) != PACKET_KEYS:
        errors.append("paper review JSON schema properties drift from checker")

    try:
        manifest = _load_yaml(manifest_path)
    except (OSError, ValueError, yaml.YAMLError) as exc:
        return {}, [f"review manifest unreadable: {exc}"]
    expected_manifest_keys = {
        "schema_version",
        "plan_id",
        "minimum_reviewers",
        "independence_rule",
        "packets",
    }
    if set(manifest) != expected_manifest_keys:
        errors.append("review manifest keys drift")
    if manifest.get("schema_version") != "1.0":
        errors.append("review manifest schema_version must be '1.0'")
    minimum = manifest.get("minimum_reviewers")
    if isinstance(minimum, bool) or not isinstance(minimum, int) or minimum < 2:
        errors.append("minimum_reviewers must be an integer >= 2")
        minimum = 2
    entries = manifest.get("packets")
    if not isinstance(entries, list) or not entries:
        errors.append("review manifest requires packets")
        entries = []

    records: list[dict[str, Any]] = []
    seen_paths: set[Path] = set()
    seen_ids: set[str] = set()
    for index, entry in enumerate(entries):
        if not isinstance(entry, dict) or set(entry) != {"path", "required_before_measurement"}:
            errors.append(f"packets[{index}] must contain path and required_before_measurement")
            continue
        required = entry["required_before_measurement"]
        if not isinstance(required, bool):
            errors.append(f"packets[{index}].required_before_measurement must be boolean")
            continue
        try:
            path = _repo_path(root, entry["path"], f"packets[{index}].path")
        except ValueError as exc:
            errors.append(str(exc))
            continue
        if path in seen_paths:
            errors.append(f"duplicate packet path: {entry['path']}")
            continue
        seen_paths.add(path)
        try:
            packet = _load_yaml(path)
        except (OSError, ValueError, yaml.YAMLError) as exc:
            errors.append(f"packet unreadable {entry['path']}: {exc}")
            continue
        errors.extend(
            validate_packet(
                packet,
                root=root,
                path=path,
                minimum_reviewers=minimum,
                required_before_measurement=required,
            )
        )
        review_id = str(packet.get("review_id", ""))
        if review_id in seen_ids:
            errors.append(f"duplicate paper review_id: {review_id}")
        seen_ids.add(review_id)
        try:
            evidence_digest = evidence_manifest_sha256(packet, root=root)
        except (OSError, ValueError):
            evidence_digest = ""
        packet_reviewers = packet.get("reviewers", [])
        reviewed_commits = sorted(
            {
                str(reviewer.get("reviewed_commit"))
                for reviewer in packet_reviewers
                if isinstance(reviewer, dict) and reviewer.get("reviewed_commit")
            }
        )
        records.append(
            {
                "review_id": review_id,
                "path": str(path.relative_to(root)),
                "status": packet.get("status"),
                "review_phase": packet.get("review_phase"),
                "final_evidence_root_sha256": packet.get("final_evidence_root_sha256"),
                "required_before_measurement": required,
                "reviewer_count": len(packet.get("reviewers", []))
                if isinstance(packet.get("reviewers"), list)
                else 0,
                "reviewed_commits": reviewed_commits,
                "evidence_manifest_sha256": evidence_digest,
            }
        )

    def reviewed_commits(selected: list[dict[str, Any]]) -> list[str]:
        return sorted(
            {
                commit
                for record in selected
                if record["status"] in {"reviewed", "disputed"}
                for commit in record["reviewed_commits"]
            }
        )

    pre = [record for record in records if record["required_before_measurement"]]
    post = [record for record in records if not record["required_before_measurement"]]
    pre_measurement_reviewed_source_commits = reviewed_commits(pre)
    post_measurement_reviewed_source_commits = reviewed_commits(post)
    reviewed_source_commits = sorted(
        {
            *pre_measurement_reviewed_source_commits,
            *post_measurement_reviewed_source_commits,
        }
    )
    if reviewed_source_commits:
        try:
            current_head = _git(root, "rev-parse", "HEAD")
            for commit in reviewed_source_commits:
                _git(root, "cat-file", "-e", f"{commit}^{{commit}}")
                _git(root, "merge-base", "--is-ancestor", commit, current_head)
                critical_drift = _git(
                    root,
                    "diff",
                    "--name-only",
                    f"{commit}..{current_head}",
                    "--",
                    "ctkat",
                    "scripts",
                    "examples",
                    "docs/measurement",
                    "docs/baselines",
                    "docs/ground_truth",
                    "pyproject.toml",
                    "uv.lock",
                )
                if critical_drift:
                    errors.append(
                        f"reviewed source commit {commit} has measurement-critical drift: "
                        + ", ".join(critical_drift.splitlines())
                    )
        except (OSError, subprocess.SubprocessError) as exc:
            errors.append(f"cannot validate reviewed source commit provenance: {exc}")
    statuses = Counter(str(record["status"]) for record in records)
    approved_final_roots = sorted(
        {
            str(record["final_evidence_root_sha256"])
            for record in post
            if record["status"] == "reviewed"
            and isinstance(record["final_evidence_root_sha256"], str)
            and SHA256_RE.fullmatch(record["final_evidence_root_sha256"])
        }
    )
    report = {
        "schema_version": "1.0",
        "kind": "paper-review-readiness",
        "generated_at": _utc_now(),
        "plan_id": manifest.get("plan_id", ""),
        "minimum_reviewers": minimum,
        "static_valid": not errors,
        "pre_measurement_ready": not errors
        and bool(pre)
        and all(
            record["status"] == "reviewed" and record["reviewer_count"] >= minimum for record in pre
        ),
        "paper_ready": not errors
        and bool(records)
        and all(
            record["status"] == "reviewed" and record["reviewer_count"] >= minimum
            for record in records
        )
        and bool(post)
        and all(
            isinstance(record["final_evidence_root_sha256"], str)
            and bool(SHA256_RE.fullmatch(record["final_evidence_root_sha256"]))
            for record in post
        )
        and len(approved_final_roots) == 1,
        "approved_final_evidence_root_sha256": (
            approved_final_roots[0] if not errors and len(approved_final_roots) == 1 else None
        ),
        "status_counts": dict(sorted(statuses.items())),
        "reviewed_source_commits": reviewed_source_commits,
        "pre_measurement_reviewed_source_commits": (pre_measurement_reviewed_source_commits),
        "post_measurement_reviewed_source_commits": (post_measurement_reviewed_source_commits),
        "packets": records,
    }
    return report, errors


def _write_json_atomic(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    os.replace(temporary, path)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--write-report", type=Path)
    parser.add_argument(
        "--expected-final-evidence-root-sha256",
        help="require the completed post-measurement packet to bind this candidate root",
    )
    readiness = parser.add_mutually_exclusive_group()
    readiness.add_argument("--require-pre-measurement", action="store_true")
    readiness.add_argument("--require-complete", action="store_true")
    args = parser.parse_args(argv)

    if args.expected_final_evidence_root_sha256 is not None:
        if not args.require_complete:
            parser.error("--expected-final-evidence-root-sha256 requires --require-complete")
        if not SHA256_RE.fullmatch(args.expected_final_evidence_root_sha256):
            parser.error("--expected-final-evidence-root-sha256 must be lowercase 64-hex")

    report, errors = evaluate_manifest(args.manifest.resolve())
    if (
        args.expected_final_evidence_root_sha256 is not None
        and report.get("approved_final_evidence_root_sha256")
        != args.expected_final_evidence_root_sha256
    ):
        errors.append(
            "completed post-measurement review does not bind the expected final evidence root"
        )
        report["static_valid"] = False
        report["paper_ready"] = False
    for error in errors:
        print(f"[paper-review] ERROR: {error}", file=sys.stderr)
    if args.write_report is not None and report:
        _write_json_atomic(args.write_report.resolve(), report)
    if errors:
        return 1
    print(json.dumps(report, indent=2, sort_keys=True))
    if args.require_pre_measurement and not report["pre_measurement_ready"]:
        return 2
    if args.require_complete and not report["paper_ready"]:
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
